openapi: 3.0.0
info:
  title: FitHub API Collection
  description: Postman collection for all endpoints in the FitHub Flask application.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
paths:
  /:
    get:
      tags:
        - default
      summary: Home Page
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /signUp:
    post:
      tags:
        - default
      summary: Role Choice
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /personal_profile:
    get:
      tags:
        - default
      summary: Personal Profile
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /editProfileTrainee:
    post:
      tags:
        - default
      summary: Edit Profile (Trainee)
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /editProfileCoach:
    post:
      tags:
        - default
      summary: Edit Profile (Coach)
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /profileTraineeStats:
    get:
      tags:
        - default
      summary: Personal Profile Stats (Trainee)
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /profileTraineePosts:
    get:
      tags:
        - default
      summary: Personal Profile Posts (Trainee)
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /profileTraineePlan:
    get:
      tags:
        - default
      summary: Personal Profile Plan (Trainee)
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /saveExercise:
    post:
      tags:
        - default
      summary: Save Exercise
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /saveAllPlan:
    post:
      tags:
        - default
      summary: Save All Plan
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /profileCoachInformation:
    get:
      tags:
        - default
      summary: Personal Profile Information (Coach)
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logout:
    get:
      tags:
        - default
      summary: Logout
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /google/:
    get:
      tags:
        - default
      summary: Google OAuth
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /google/auth/:
    get:
      tags:
        - default
      summary: OAuth Google Authentication
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /posts:
    get:
      tags:
        - default
      summary: Posts
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /add_comment/{post_id}:
    post:
      tags:
        - default
      summary: Add Comment
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: post_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /chats:
    get:
      tags:
        - default
      summary: Chats
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /send_message:
    post:
      tags:
        - default
      summary: Send Message
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /add_recipe:
    post:
      tags:
        - default
      summary: Add Recipe
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /recipes:
    get:
      tags:
        - default
      summary: Get Recipes
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /recipes/{recipe_id}:
    get:
      tags:
        - default
      summary: Recipe Details
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: recipe_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /coaches:
    get:
      tags:
        - default
      summary: Get Coaches
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /exercises:
    get:
      tags:
        - default
      summary: Get Exercises
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /exercise/{exercise_id}:
    get:
      tags:
        - default
      summary: Exercise Details
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
        - name: exercise_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /add_exercises:
    post:
      tags:
        - default
      summary: Add Exercise
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{}"'
      parameters:
        - name: Content-Type
          in: header
          schema:
            type: string
          example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}